name: build
on:
  push:
    branches:
      - master
env:
  SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
  SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
  API_URL: ${{ secrets.API_URL }}
jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
          cache: 'pnpm'
      - name: install and build
        run: |
          pnpm install --prod
          pnpm run build
      - name: deploy
        run: |
          pnpm install -g surge
          surge ./dist/ sfn.sheev.net